[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = nodemcu
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.partitions = huge_app.csv
monitor_filters = direct

; Bluetooth và I2S support
build_flags =
    -DBLUETOOTH_ENABLED
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_ENABLED
    -DCONFIG_BLUEDROID_ENABLED
    -Os
    

lib_deps =
    dfrobot/DFRobotDFPlayerMini
    bblanchon/ArduinoJson 
